apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ziti-controller
  namespace: ziti
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2
