apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    name: trust-manager
    namespace: ziti

  spec:
    selfSigned: {}
- apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    name: ziti-controller-ctrl-plane-intermediate-issuer
    namespace: ziti

  spec:
    ca:
      secretName: ziti-controller-ctrl-plane-intermediate-secret
- apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    name: ziti-controller-ctrl-plane-root-issuer
    namespace: ziti

  spec:
    ca:
      secretName: ziti-controller-ctrl-plane-root-secret
- apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    name: ziti-controller-edge-root-issuer
    namespace: ziti

  spec:
    ca:
      secretName: ziti-controller-edge-root-secret
- apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    name: ziti-controller-edge-signer-issuer
    namespace: ziti

  spec:
    ca:
      secretName: ziti-controller-edge-signer-secret
- apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    name: ziti-controller-selfsigned-ca-issuer
    namespace: ziti

  spec:
    selfSigned: {}
- apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    name: ziti-controller-web-intermediate-issuer
    namespace: ziti

  spec:
    ca:
      secretName: ziti-controller-web-intermediate-secret
- apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    name: ziti-controller-web-root-issuer
    namespace: ziti

  spec:
    ca:
      secretName: ziti-controller-web-root-secret
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: trust-manager
    namespace: ziti
  spec:
    dnsNames:
    - trust-manager.ziti.svc
    issuerRef:
      group: cert-manager.io
      kind: Issuer
      name: trust-manager
    revisionHistoryLimit: 1
    secretName: trust-manager-tls
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ziti-controller-admin-client-cert
    namespace: ziti
  spec:
    commonName: ziti-controller-admin
    duration: 8760h0m0s
    issuerRef:
      kind: Issuer
      name: ziti-controller-edge-signer-issuer
    privateKey:
      algorithm: ECDSA
      size: 256
    renewBefore: 720h0m0s
    secretName: ziti-controller-admin-client-secret
    usages:
    - client auth
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ziti-controller-ctrl-plane-identity
    namespace: ziti

  spec:
    commonName: ziti-controller-ctrl-plane-identity
    dnsNames:
    - localhost
    - ziti-controller
    - ziti-controller-ctrl
    - ziti-controller-ctrl.ziti
    - ziti-controller-ctrl.ziti.svc
    - ziti-controller-ctrl.ziti.svc.cluster.local
    - ac931276698954fb897c7a285885ad8c-2058336563.eu-north-1.elb.amazonaws.com
    duration: 87840h0m0s
    ipAddresses:
    - 127.0.0.1
    issuerRef:
      kind: Issuer
      name: ziti-controller-ctrl-plane-intermediate-issuer
    privateKey:
      algorithm: RSA
      size: 4096
    renewBefore: 720h0m0s
    secretName: ziti-controller-ctrl-plane-identity-secret
    usages:
    - client auth
    - server auth
    - digital signature
    - content commitment
    - key encipherment
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ziti-controller-ctrl-plane-intermediate-cert
    namespace: ziti

  spec:
    commonName: ziti-controller-ctrl-plane-intermediate
    duration: 87840h0m0s
    isCA: true
    issuerRef:
      kind: Issuer
      name: ziti-controller-ctrl-plane-root-issuer
    privateKey:
      algorithm: ECDSA
      size: 256
    renewBefore: 720h0m0s
    secretName: ziti-controller-ctrl-plane-intermediate-secret
    usages:
    - digital signature
    - cert sign
    - crl sign
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ziti-controller-ctrl-plane-root-cert
    namespace: ziti

  spec:
    commonName: ziti-controller-ctrl-plane-root
    duration: 876000h0m0s
    isCA: true
    issuerRef:
      kind: Issuer
      name: ziti-controller-selfsigned-ca-issuer
    privateKey:
      algorithm: ECDSA
      size: 256
    renewBefore: 720h0m0s
    secretName: ziti-controller-ctrl-plane-root-secret
    usages:
    - digital signature
    - cert sign
    - crl sign
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ziti-controller-edge-intermediate-cert
    namespace: ziti

  spec:
    commonName: ziti-controller-edge-intermediate
    duration: 87840h0m0s
    isCA: true
    issuerRef:
      kind: Issuer
      name: ziti-controller-edge-root-issuer
    privateKey:
      algorithm: ECDSA
      size: 256
    renewBefore: 720h0m0s
    secretName: ziti-controller-edge-intermediate-secret
    usages:
    - digital signature
    - cert sign
    - crl sign
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ziti-controller-edge-root-cert
    namespace: ziti

  spec:
    commonName: ziti-controller-edge-root
    duration: 876000h0m0s
    isCA: true
    issuerRef:
      kind: Issuer
      name: ziti-controller-selfsigned-ca-issuer
    privateKey:
      algorithm: ECDSA
      size: 256
    renewBefore: 720h0m0s
    secretName: ziti-controller-edge-root-secret
    usages:
    - digital signature
    - cert sign
    - crl sign
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ziti-controller-edge-signer-cert
    namespace: ziti

  spec:
    commonName: ziti-controller-edge-signer
    duration: 87840h0m0s
    isCA: true
    issuerRef:
      kind: Issuer
      name: ziti-controller-edge-intermediate-issuer
    privateKey:
      algorithm: ECDSA
      size: 256
    renewBefore: 720h0m0s
    secretName: ziti-controller-edge-signer-secret
    usages:
    - digital signature
    - cert sign
    - crl sign
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ziti-controller-web-identity-cert
    namespace: ziti

  spec:
    commonName: ziti-controller-web-identity
    dnsNames:
    - localhost
    - ziti-controller
    - ziti-controller-client
    - ziti-controller-client.ziti
    - ziti-controller-client.ziti.svc
    - ziti-controller-client.ziti.svc.cluster.local
    - aedc36dd9af28431ca7573410e80e3cf-1954417305.eu-north-1.elb.amazonaws.com
    duration: 87840h0m0s
    ipAddresses:
    - 127.0.0.1
    issuerRef:
      kind: Issuer
      name: ziti-controller-web-intermediate-issuer
    privateKey:
      algorithm: RSA
      size: 4096
    renewBefore: 720h0m0s
    secretName: ziti-controller-web-identity-secret
    usages:
    - client auth
    - server auth
    - digital signature
    - content commitment
    - key encipherment
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ziti-controller-web-intermediate-cert
    namespace: ziti

  spec:
    commonName: ziti-controller-web-intermediate
    duration: 87840h0m0s
    isCA: true
    issuerRef:
      kind: Issuer
      name: ziti-controller-web-root-issuer
    privateKey:
      algorithm: ECDSA
      size: 256
    renewBefore: 720h0m0s
    secretName: ziti-controller-web-intermediate-secret
    usages:
    - digital signature
    - cert sign
    - crl sign
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ziti-controller-web-root-cert
    namespace: ziti

  spec:
    commonName: ziti-controller-web-root
    duration: 876000h0m0s
    isCA: true
    issuerRef:
      kind: Issuer
      name: ziti-controller-selfsigned-ca-issuer
    privateKey:
      algorithm: ECDSA
      size: 256
    renewBefore: 720h0m0s
    secretName: ziti-controller-web-root-secret
    usages:
    - digital signature
    - cert sign
    - crl sign
kind: List
metadata:
  resourceVersion: ""