apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziti-tunnel-sidecar-demo
  namespace: external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ziti-tunnel-sidecar-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ziti-tunnel-sidecar-demo
    spec:
      containers:
        - image: alpine:3.12.2
          name: testclient
          command: ["sh", "-c", "apk add --no-cache curl && curl -s hello.ziti.internal && echo 'Connection successful' || echo 'Connection failed'"]

        - image: openziti/ziti-tunnel
          name: ziti-tunnel
          args: ["tproxy"]
          env:
          - name: ZITI_IDENTITY_BASENAME
            value: c2-hello-client  
          volumeMounts:
          - name: c2-hello-client
            mountPath: /netfoundry
            readOnly: true
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 127.0.0.1   # used by the tunneler during startup to verify own DNS for the pod
          - 10.100.0.10  # change to CoreDNS cluster service address
      restartPolicy: Always
      volumes:
      - name: c2-hello-client
        secret:
          secretName: c2-hello-client


        



