apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziti-tunnel-sidecar-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ziti-tunnel-sidecar-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ziti-tunnel-sidecar-demo
    spec:
      containers:
        - image: alpine:3.12.2
          name: testclient
          command: ["sh", "-c", "apk add --no-cache curl && curl -s http://vault1.ziti.internal:8203 && echo 'Connection successful' || echo 'Connection failed'"]
      restartPolicy: Always

