apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziti-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ziti-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ziti-test
    spec:
      containers:
        - image: alpine:3.12.2
          name: testclient
          command: ["sh", "-c", "apk add --no-cache curl && curl -s http://postgres.ziti.internal && echo 'Connection successful' || echo 'Connection failed'"]
      restartPolicy: Always

