apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets
    helm.sh/chart: external-secrets-0.9.19
  name: external-secrets
  namespace: external-secrets
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: external-secrets
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: external-secrets
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: external-secrets
        app.kubernetes.io/version: v0.9.19
        helm.sh/chart: external-secrets-0.9.19
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --concurrent=1
        - --metrics-addr=:8080
        image: ghcr.io/external-secrets/external-secrets:v0.9.19
        imagePullPolicy: IfNotPresent
        name: external-secrets
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop: []
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: openziti/ziti-tunnel
        name: ziti-tunnel
        args: ["tproxy"]
        env:
        - name: ZITI_IDENTITY_BASENAME
          value: vault-client 
        volumeMounts:
        - name: vault-client
          mountPath: /netfoundry
          readOnly: true
        securityContext:
          capabilities:
            add:
            - NET_ADMIN      
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 127.0.0.1   # used by the tunneler during startup to verify own DNS for the pod
          - 172.20.0.10       
      restartPolicy: Always
      volumes:
      - name: vault-client
        secret:
          secretName: vault-client     
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: external-secrets
      serviceAccountName: external-secrets
      terminationGracePeriodSeconds: 30

  